/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-page': '#FFF9F3',
        'bg-card': '#FFFFFF',
        'bg-card-masse': '#FFF0E6',
        'bg-card-seche': '#EEFAE6',
        'bg-input': '#FFFFFF',
        'bg-nav': '#FFF5ED',
        'bg-section': '#FFF5ED',
        'primary': '#E8713A',
        'primary-hover': '#D4612E',
        'primary-light': '#FAECE7',
        'secondary': '#E8B44A',
        'secondary-light': '#FAEEDA',
        'masse': '#D85A30',
        'masse-bg': '#FFF0E6',
        'masse-light': '#FAECE7',
        'seche': '#5AAD2F',
        'seche-bg': '#EEFAE6',
        'seche-light': '#EAF3DE',
        'cal-bg': '#FAEEDA',
        'cal-text': '#854F0B',
        'prot-bg': '#FAECE7',
        'prot-text': '#993C1D',
        'carb-bg': '#EAF3DE',
        'carb-text': '#3B6D11',
        'fat-bg': '#FBEAF0',
        'fat-text': '#72243E',
        'text-primary': '#2C2420',
        'text-secondary': '#8A7D74',
        'text-muted': '#B5A99E',
        'border-default': '#E8DDD3',
        'border-strong': '#2C2420',
      },
      fontFamily: {
        fredoka: ['Fredoka', 'sans-serif'],
        nunito: ['Nunito', 'sans-serif'],
      },
      borderRadius: {
        card: '16px',
        pill: '50px',
        macro: '10px',
        input: '12px',
        nav: '12px',
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        'card-hover': '0 8px 20px rgba(44, 36, 32, 0.08)',
        'btn-hover': '0 4px 12px rgba(232, 113, 58, 0.25)',
        'nav-active': '0 2px 8px rgba(232, 113, 58, 0.2)',
        modal: '0 12px 32px rgba(44, 36, 32, 0.12)',
      },
    },
  },
  plugins: [],
}
